<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Modelo;
use App\Models\Marca;
use App\Models\SistemaOperativo;

class ModeloSeeder extends Seeder
{
    public function run()
    {
        $ios = SistemaOperativo::where('nombre', 'iOS')->first();
        $android = SistemaOperativo::where('nombre', 'Android')->first();

        $apple = Marca::where('nombre', 'Apple')->first();
        $samsung = Marca::where('nombre', 'Samsung')->first();
        $xiaomi = Marca::where('nombre', 'Xiaomi')->first();
        $google = Marca::where('nombre', 'Google')->first();

        $modelos = [
            // APPLE
            [
                'nombre' => 'iPhone 15',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A16 Bionic',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 3349,
                'pantalla_pulgadas' => 6.1,
                'hz_pantalla' => 60,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'iPhone 16',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A18',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 3561,
                'pantalla_pulgadas' => 6.1,
                'hz_pantalla' => 60,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'iPhone 16 Pro',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A18 Pro',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 3582,
                'pantalla_pulgadas' => 6.3,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'iPhone 17',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A19',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 18,
                'bateria_mah' => 3692,
                'pantalla_pulgadas' => 6.3,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'iPhone 17 Pro',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A19 Pro',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 18,
                'bateria_mah' => 3988,
                'pantalla_pulgadas' => 6.3,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'iPhone Air',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A19 Pro',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 18,
                'bateria_mah' => 3149,
                'pantalla_pulgadas' => 6.5,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'eSIM',
            ],

            // SAMSUNG
            [
                'nombre' => 'Galaxy A16',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Exynos 1330 / Dimensity 6300',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 13,
                'bateria_mah' => 5000,
                'pantalla_pulgadas' => 6.7,
                'hz_pantalla' => 90,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Galaxy A56',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Exynos 1580',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 5000,
                'pantalla_pulgadas' => 6.7,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Galaxy S25',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Snapdragon 8 Elite for Galaxy',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 4000,
                'pantalla_pulgadas' => 6.2,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'Galaxy Z Flip',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Snapdragon 8 Gen 3 for Galaxy',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 10,
                'bateria_mah' => 4000,
                'pantalla_pulgadas' => 6.7,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],

            // GOOGLE
            [
                'nombre' => 'Google Pixel 7 Pro',
                'marca_id' => $google?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Google Tensor G2',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 10,
                'bateria_mah' => 5000,
                'pantalla_pulgadas' => 6.7,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'Google Pixel 8 Pro',
                'marca_id' => $google?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Google Tensor G3',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 10,
                'bateria_mah' => 5050,
                'pantalla_pulgadas' => 6.7,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'Google Pixel 9 Pro',
                'marca_id' => $google?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Google Tensor G4',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 42,
                'bateria_mah' => 4700,
                'pantalla_pulgadas' => 6.3,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'Google Pixel 10 Pro',
                'marca_id' => $google?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Google Tensor G5',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 42,
                'bateria_mah' => 4970,
                'pantalla_pulgadas' => 6.3,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],

            // XIAOMI / REDMI
            [
                'nombre' => 'Redmi A5',
                'marca_id' => $xiaomi?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Unisoc T7250',
                'cinco_g' => false,
                'camara_principal_mp' => 32,
                'camara_frontal_mp' => 8,
                'bateria_mah' => 5200,
                'pantalla_pulgadas' => 6.88,
                'hz_pantalla' => 120,
                'nfc' => false,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Redmi Note 13',
                'marca_id' => $xiaomi?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'MediaTek Dimensity 6080',
                'cinco_g' => true,
                'camara_principal_mp' => 108,
                'camara_frontal_mp' => 16,
                'bateria_mah' => 5000,
                'pantalla_pulgadas' => 6.67,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Redmi Note 14',
                'marca_id' => $xiaomi?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'MediaTek Helio G99-Ultra',
                'cinco_g' => false,
                'camara_principal_mp' => 108,
                'camara_frontal_mp' => 20,
                'bateria_mah' => 5500,
                'pantalla_pulgadas' => 6.67,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Redmi Note 15',
                'marca_id' => $xiaomi?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'MediaTek Helio G100-Ultra',
                'cinco_g' => false,
                'camara_principal_mp' => 108,
                'camara_frontal_mp' => 8,
                'bateria_mah' => 6000,
                'pantalla_pulgadas' => 6.77,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Xiaomi 14',
                'marca_id' => $xiaomi?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Snapdragon 8 Gen 3',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 32,
                'bateria_mah' => 4610,
                'pantalla_pulgadas' => 6.36,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Xiaomi 14 Pro',
                'marca_id' => $xiaomi?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Snapdragon 8 Gen 3',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 32,
                'bateria_mah' => 4880,
                'pantalla_pulgadas' => 6.73,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Redmi 14C',
                'marca_id' => $xiaomi?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'MediaTek Helio G91 Ultra',
                'cinco_g' => false,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 13,
                'bateria_mah' => 5160,
                'pantalla_pulgadas' => 6.88,
                'hz_pantalla' => 90,
                'nfc' => false,
                'tipo_sim' => 'Dual SIM',
            ],

            // SAMSUNG (adicionales)
            [
                'nombre' => 'Galaxy A35',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Exynos 1380',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 13,
                'bateria_mah' => 5000,
                'pantalla_pulgadas' => 6.6,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'Dual SIM',
            ],
            [
                'nombre' => 'Galaxy S25+',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Snapdragon 8 Elite for Galaxy',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 4900,
                'pantalla_pulgadas' => 6.7,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'Galaxy S25 Ultra',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Snapdragon 8 Elite for Galaxy',
                'cinco_g' => true,
                'camara_principal_mp' => 200,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 5000,
                'pantalla_pulgadas' => 6.9,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'Galaxy Z Fold 6',
                'marca_id' => $samsung?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Snapdragon 8 Gen 3 for Galaxy',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 10,
                'bateria_mah' => 4400,
                'pantalla_pulgadas' => 7.6,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],

            // APPLE (adicionales)
            [
                'nombre' => 'iPhone 14',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A15 Bionic',
                'cinco_g' => true,
                'camara_principal_mp' => 12,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 3279,
                'pantalla_pulgadas' => 6.1,
                'hz_pantalla' => 60,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'iPhone 16 Plus',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A18',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 4674,
                'pantalla_pulgadas' => 6.7,
                'hz_pantalla' => 60,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'iPhone 16 Pro Max',
                'marca_id' => $apple?->id,
                'sistema_operativo_id' => $ios?->id,
                'conector' => 'Type-C',
                'procesador' => 'A18 Pro',
                'cinco_g' => true,
                'camara_principal_mp' => 48,
                'camara_frontal_mp' => 12,
                'bateria_mah' => 4685,
                'pantalla_pulgadas' => 6.9,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],

            // GOOGLE (adicionales)
            [
                'nombre' => 'Google Pixel 8a',
                'marca_id' => $google?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Google Tensor G3',
                'cinco_g' => true,
                'camara_principal_mp' => 64,
                'camara_frontal_mp' => 13,
                'bateria_mah' => 4492,
                'pantalla_pulgadas' => 6.1,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
            [
                'nombre' => 'Google Pixel 9',
                'marca_id' => $google?->id,
                'sistema_operativo_id' => $android?->id,
                'conector' => 'Type-C',
                'procesador' => 'Google Tensor G4',
                'cinco_g' => true,
                'camara_principal_mp' => 50,
                'camara_frontal_mp' => 10,
                'bateria_mah' => 4700,
                'pantalla_pulgadas' => 6.3,
                'hz_pantalla' => 120,
                'nfc' => true,
                'tipo_sim' => 'SIM + eSIM',
            ],
        ];

        foreach ($modelos as $modelo) {
            if (!$modelo['marca_id'] || !$modelo['sistema_operativo_id']) {
                continue;
            }

            Modelo::updateOrCreate(
                [
                    'nombre' => $modelo['nombre'],
                    'marca_id' => $modelo['marca_id'],
                ],
                [
                    'sistema_operativo_id' => $modelo['sistema_operativo_id'],
                    'conector' => $modelo['conector'],
                    'procesador' => $modelo['procesador'],
                    'cinco_g' => $modelo['cinco_g'],
                    'camara_principal_mp' => $modelo['camara_principal_mp'],
                    'camara_frontal_mp' => $modelo['camara_frontal_mp'],
                    'bateria_mah' => $modelo['bateria_mah'],
                    'pantalla_pulgadas' => $modelo['pantalla_pulgadas'],
                    'hz_pantalla' => $modelo['hz_pantalla'],
                    'nfc' => $modelo['nfc'],
                    'tipo_sim' => $modelo['tipo_sim'],
                ]
            );
        }
    }
}
